<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class T_output_model extends CI_Model
{

    public $table = 't_output';
    public $id = 'id_output';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_output,KDGIAT,KDOUTPUT,NMOUTPUT,SAT,KDSUM,THNAWAL,THNAKHIR,KDMULTI,KDJNSOUT,KDIKK,KDTEMA,KDCTTOUT');
        $this->datatables->from('t_output');
        //add this line for join
        //$this->datatables->join('table2', 't_output.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('t_output/read/$1'),'Read')." | ".anchor(site_url('t_output/update/$1'),'Update')." | ".anchor(site_url('t_output/delete/$1'),'Delete','onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_output');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_output', $q);
	$this->db->or_like('KDGIAT', $q);
	$this->db->or_like('KDOUTPUT', $q);
	$this->db->or_like('NMOUTPUT', $q);
	$this->db->or_like('SAT', $q);
	$this->db->or_like('KDSUM', $q);
	$this->db->or_like('THNAWAL', $q);
	$this->db->or_like('THNAKHIR', $q);
	$this->db->or_like('KDMULTI', $q);
	$this->db->or_like('KDJNSOUT', $q);
	$this->db->or_like('KDIKK', $q);
	$this->db->or_like('KDTEMA', $q);
	$this->db->or_like('KDCTTOUT', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_output', $q);
	$this->db->or_like('KDGIAT', $q);
	$this->db->or_like('KDOUTPUT', $q);
	$this->db->or_like('NMOUTPUT', $q);
	$this->db->or_like('SAT', $q);
	$this->db->or_like('KDSUM', $q);
	$this->db->or_like('THNAWAL', $q);
	$this->db->or_like('THNAKHIR', $q);
	$this->db->or_like('KDMULTI', $q);
	$this->db->or_like('KDJNSOUT', $q);
	$this->db->or_like('KDIKK', $q);
	$this->db->or_like('KDTEMA', $q);
	$this->db->or_like('KDCTTOUT', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file T_output_model.php */
/* Location: ./application/models/T_output_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-11-14 14:40:26 */
/* http://harviacode.com */